# Generated by Django 5.1.7 on 2025-04-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_address_manufacturer_headquarters_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(default='select', max_length=255),
        ),
    ]
