# Generated by Django 5.1.7 on 2025-04-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_manufacturer_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
